// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Alliance struct {
	Name          *string   `json:"name"`
	Tag           string    `json:"tag"`
	AllianceID    string    `json:"alliance_id"`
	Region        string    `json:"region"`
	SkipNameCheck bool      `json:"skip_name_check"`
	FirstSeen     time.Time `json:"first_seen"`
	LastSeen      time.Time `json:"last_seen"`
}

type Guild struct {
	Name      string    `json:"name"`
	GuildID   string    `json:"guild_id"`
	Region    string    `json:"region"`
	FirstSeen time.Time `json:"first_seen"`
	LastSeen  time.Time `json:"last_seen"`
}

type GuildAllianceMembership struct {
	ID         pgtype.UUID `json:"id"`
	GuildID    string      `json:"guild_id"`
	AllianceID string      `json:"alliance_id"`
	Region     string      `json:"region"`
	IsActive   bool        `json:"is_active"`
	FirstSeen  time.Time   `json:"first_seen"`
	LastSeen   time.Time   `json:"last_seen"`
}

type Player struct {
	Name       string    `json:"name"`
	PlayerID   string    `json:"player_id"`
	Region     string    `json:"region"`
	Avatar     *string   `json:"avatar"`
	AvatarRing *string   `json:"avatar_ring"`
	FirstSeen  time.Time `json:"first_seen"`
	LastSeen   time.Time `json:"last_seen"`
}

type PlayerGuildMembership struct {
	ID        pgtype.UUID `json:"id"`
	PlayerID  string      `json:"player_id"`
	GuildID   string      `json:"guild_id"`
	Region    string      `json:"region"`
	IsActive  bool        `json:"is_active"`
	FirstSeen time.Time   `json:"first_seen"`
	LastSeen  time.Time   `json:"last_seen"`
}
